api_key: "API_KEY_____________________________________________________________"
base_url: "https://api.openai.com/v1/chat/completions"
model_name: "gpt-4o"
max_tokens: 4096
input_folder: 'input'
temperature: 0
top_p: 0
n: 1
stop: None
presence_penalty: 0.0
frequency_penalty: 0.0


